-- Seed questions for "MCU Spiderman" (Subject ID: 3)
INSERT INTO questions (subject_id, question, options, answer) VALUES
(3, 'What is the name of Peter Parker''s high school in the MCU?', '{"Midtown School of Science and Technology", "Queens High School", "Brooklyn Technical High School", "Stark Academy"}', 'Midtown School of Science and Technology'),
(3, 'Who is Peter Parker''s best friend in the MCU?', '{"Ned Leeds", "Harry Osborn", "Flash Thompson", "MJ"}', 'Ned Leeds'),
(3, 'What superhero team does Spider-Man fight with in "Captain America: Civil War"?', '{"The Avengers", "The Guardians of the Galaxy", "The Defenders", "The X-Men"}', 'The Avengers'),
(3, 'Who gives Peter Parker his upgraded Spider-Man suit in the MCU?', '{"Tony Stark", "Bruce Banner", "Nick Fury", "Stephen Strange"}', 'Tony Stark'),
(3, 'What is the name of the AI in Spider-Man''s suit in "Spider-Man: Homecoming"?', '{"Friday", "Karen", "Edith", "Jarvis"}', 'Karen'),
(3, 'Which villain does Spider-Man fight in "Spider-Man: Homecoming"?', '{"Vulture", "Mysterio", "Sandman", "Doctor Octopus"}', 'Vulture'),
(3, 'What is the name of the technology that creates illusions in "Spider-Man: Far From Home"?', '{"BARF", "STARK", "EDITH", "AIDA"}', 'EDITH'),
(3, 'Who is the main antagonist in "Spider-Man: Far From Home"?', '{"Vulture", "Mysterio", "Shocker", "Green Goblin"}', 'Mysterio'),
(3, 'Where does Peter go on his school trip in "Spider-Man: Far From Home"?', '{"France", "Italy", "Germany", "Spain"}', 'Italy'),
(3, 'What is Peter Parker''s aunt''s name in the MCU?', '{"May Parker", "Mary Parker", "Anna Watson", "Betty Brant"}', 'May Parker'),
(3, 'Who figures out Peter Parker is Spider-Man in "Spider-Man: Homecoming"?', '{"Liz Allan", "Michelle Jones", "Flash Thompson", "Ned Leeds"}', 'Ned Leeds'),
(3, 'What is the name of the group of villains in "Spider-Man: Homecoming" who use alien technology?', '{"The Collectors", "The Salvagers", "The Scavengers", "The Dealers"}', 'The Salvagers'),
(3, 'What gift does Tony Stark give Peter at the end of "Spider-Man: Homecoming"?', '{"A new car", "An Avengers membership", "A suit upgrade", "A scholarship"}', 'A suit upgrade'),
(3, 'In "Spider-Man: No Way Home", who are the first two villains that appear from the multiverse?', '{"Green Goblin and Doctor Octopus", "Electro and Sandman", "Vulture and Mysterio", "Rhino and Lizard"}', 'Doctor Octopus and Green Goblin'),
(3, 'What does Peter use to trap Doctor Strange in the Mirror Dimension?', '{"Web-shooters", "Magic", "Geometry", "Time manipulation"}', 'Geometry'),
(3, 'What is MJ''s real name in the MCU?', '{"Mary Jane Watson", "Michelle Jones", "Marie Jane Watson", "Michelle Johnson"}', 'Michelle Jones'),
(3, 'Who helps Peter Parker create new web-fluid in "Spider-Man: No Way Home"?', '{"Doctor Strange", "Ned Leeds", "MJ", "Aunt May"}', 'Ned Leeds'),
(3, 'What spell does Peter ask Doctor Strange to cast in "Spider-Man: No Way Home"?', '{"Make everyone forget he is Spider-Man", "Bring back Tony Stark", "Make him invincible", "Make him the smartest person"}', 'Make everyone forget he is Spider-Man'),
(3, 'What is the theme of the homecoming dance in "Spider-Man: Homecoming"?', '{"Under the Stars", "Night to Remember", "Hollywood Nights", "Evening in Paris"}', 'Evening in Paris'),
(3, 'Who destroys the Stark Industries plane in "Spider-Man: Homecoming"?', '{"The Vulture", "Spider-Man", "The Scorpion", "The Shocker"}', 'The Vulture'),
(3, 'What nickname does Tony Stark give to Peter Parker?', '{"Underoos", "Spidey", "Webhead", "Kid"}', 'Underoos'),
(3, 'In which movie does Spider-Man first appear in the MCU?', '{"Spider-Man: Homecoming", "Captain America: Civil War", "Avengers: Infinity War", "Iron Man 2"}', 'Captain America: Civil War'),
(3, 'What major event does Peter Parker miss due to the events of "Spider-Man: Homecoming"?', '{"His science fair", "His homecoming dance", "A field trip", "His birthday"}', 'His homecoming dance'),
(3, 'How does Mysterio manipulate Peter Parker in "Spider-Man: Far From Home"?', '{"Pretends to be his uncle", "Uses mind control", "Fakes being a hero from another Earth", "Blackmails him"}', 'Fakes being a hero from another Earth'),
(3, 'What is Peter''s main goal in "Spider-Man: Far From Home" during the school trip?', '{"To stop Mysterio", "To enjoy the trip", "To reveal his identity to MJ", "To confess his feelings to MJ"}', 'To confess his feelings to MJ'),
(3, 'Who is responsible for exposing Peter Parker''s identity as Spider-Man at the end of "Spider-Man: Far From Home"?', '{"Nick Fury", "Mysterio", "Vulture", "J. Jonah Jameson"}', 'Mysterio'),
(3, 'What type of creature are the Elementals in "Spider-Man: Far From Home"?', '{"Aliens", "Robots", "Magical beings", "Illusions"}', 'Illusions'),
(3, 'Which Avenger''s weapon does Spider-Man use to defeat Thanos'' army in "Avengers: Endgame"?', '{"Captain America''s shield", "Thor''s hammer", "Iron Man''s gauntlet", "Hawkeye''s bow"}', 'Captain America''s shield'),
(3, 'In "Spider-Man: No Way Home", which character from previous Spider-Man films helps Peter understand the multiverse?', '{"Doctor Octopus", "Electro", "Green Goblin", "Doctor Strange"}', 'Doctor Strange'),
(3, 'What is the high-tech glasses called that Tony Stark bequeaths to Peter in "Spider-Man: Far From Home"?', '{"STARK EYE", "EDITH", "JARVIS", "FRIDAY"}', 'EDITH'),
(3, 'What device does Peter invent to help defeat the drones in "Spider-Man: Far From Home"?', '{"Web grenades", "Drone disruptor", "Stealth suit", "Electro web"}', 'Web grenades'),
(3, 'Who does Peter Parker entrust with his secret identity besides MJ and Ned in the MCU?', '{"Flash Thompson", "Aunt May", "Liz Allan", "None"}', 'Aunt May'),
(3, 'In "Spider-Man: Homecoming", what does Peter do to stop Vulture from selling stolen alien technology?', '{"Calls Tony Stark", "Infiltrates his gang", "Sets a trap", "Steals the technology back"}', 'Sets a trap'),
(3, 'What job does Aunt May take on in "Spider-Man: Far From Home"?', '{"Teacher", "Nurse", "Charity worker", "Government agent"}', 'Charity worker'),
(3, 'Who is the first person Peter reveals his Spider-Man identity to in "Spider-Man: Homecoming"?', '{"Liz Allan", "MJ", "Ned Leeds", "Aunt May"}', 'Ned Leeds'),
(3, 'What material is the new suit made of that Peter designs in "Spider-Man: Far From Home"?', '{"Vibranium", "Stark-enhanced fabric", "Spider silk", "Nano-tech"}', 'Stark-enhanced fabric'),
(3, 'Who captures Peter and interrogates him in "Spider-Man: Homecoming"?', '{"The FBI", "The Vulture", "The CIA", "SHIELD"}', 'The Vulture'),
(3, 'What is the fake name of the superhero persona Mysterio uses in "Spider-Man: Far From Home"?', '{"Mystic Warrior", "Quantum Man", "Elemental Master", "None, just Mysterio"}', 'None, just Mysterio'),
(3, 'What does Peter try to buy in Venice in "Spider-Man: Far From Home" to impress MJ?', '{"A glass necklace", "A diamond ring", "A black dahlia", "Venetian mask"}', 'A black dahlia'),
(3, 'How does Peter finally defeat Mysterio in "Spider-Man: Far From Home"?', '{"Using his \"Peter Tingle\"", "With Tony Stark''s help", "Using Doctor Strange''s spells", "By hacking the drones"}', 'Using his \"Peter Tingle\"');
