-- Seed questions for "Next-gen Spiderman" (Subject ID: 4)
INSERT INTO questions (subject_id, question, options, answer) VALUES
(4, 'What is the full name of Next-Gen Spider-Man?', '{"Miles Morales", "Miles Davis", "Miles Johnson", "Miles Parker"}', 'Miles Morales'),
(4, 'In "Spider-Man: Into the Spider-Verse", who is Miles Morales'' mentor?', '{"Peter B. Parker", "Gwen Stacy", "Peter Parker", "Ben Parker"}', 'Peter B. Parker'),
(4, 'Which unique ability does Miles Morales possess that other Spider-People do not?', '{"Invisibility", "Flying", "Telekinesis", "Super strength"}', 'Invisibility'),
(4, 'What is the name of the machine that brings multiple Spider-People into Miles'' universe?', '{"Collider", "Multiverse Machine", "Web Weaver", "Spider Generator"}', 'Collider'),
(4, 'Who is the main antagonist in "Spider-Man: Into the Spider-Verse"?', '{"Kingpin", "Green Goblin", "Doctor Octopus", "Vulture"}', 'Kingpin'),
(4, 'What tragic event motivates Miles to fully embrace his role as Spider-Man?', '{"The death of his uncle", "The death of his father", "The city under attack", "The death of Peter Parker"}', 'The death of his uncle'),
(4, 'Which character is NOT one of the Spider-People that teams up with Miles in "Into the Spider-Verse"?', '{"Spider-Man Noir", "Spider-Ham", "Spider-Woman", "Iron Spider"}', 'Iron Spider'),
(4, 'What school does Miles Morales attend when he becomes Spider-Man?', '{"Brooklyn Visions Academy", "Midtown High School", "New York Science Academy", "Queens Metropolitan High"}', 'Brooklyn Visions Academy'),
(4, 'What musical talent does Miles Morales have?', '{"Playing guitar", "DJing", "Singing", "Playing drums"}', 'DJing'),
(4, 'What is the relation of Aaron Davis to Miles Morales?', '{"Father", "Brother", "Uncle", "Cousin"}', 'Uncle'),
(4, 'What iconic Spider-Man phrase does Miles struggle to relate to initially?', '{"With great power, comes great responsibility", "Anyone can wear the mask", "Keep moving forward", "The world needs heroes"}', 'With great power, comes great responsibility'),
(4, 'Who teaches Miles to swing from webs effectively?', '{"Gwen Stacy", "Peter B. Parker", "Spider-Man Noir", "Spider-Ham"}', 'Peter B. Parker'),
(4, 'Which character becomes the Prowler in "Into the Spider-Verse"?', '{"Jefferson Davis", "Aaron Davis", "Norman Osborn", "Harry Osborn"}', 'Aaron Davis'),
(4, 'What is the color of Miles Morales'' original Spider-Man suit?', '{"Red and Blue", "Black and Red", "Green and Yellow", "White and Purple"}', 'Black and Red'),
(4, 'Who discovers Miles'' identity as Spider-Man by the end of the movie?', '{"His father", "His mother", "His school principal", "No one"}', 'His father'),
(4, 'What is Miles Morales afraid of when he first gets his powers?', '{"Being different", "Heights", "Failure", "Being alone"}', 'Heights'),
(4, 'In "Into the Spider-Verse", what does Miles use to camouflage himself?', '{"A special suit", "Mud", "A hologram device", "His spider powers"}', 'His spider powers'),
(4, 'What does Miles Morales spray paint on his first Spider suit?', '{"A spider", "A web", "A logo", "His name"}', 'A spider'),
(4, 'What item does Miles Morales use to express his feelings through art?', '{"Spray paint", "Pencils", "Markers", "Digital tablet"}', 'Spray paint'),
(4, 'Who encourages Miles to finish what the original Spider-Man started?', '{"Peter B. Parker", "Gwen Stacy", "Jefferson Davis", "Spider-Woman"}', 'Peter B. Parker'),
(4, 'What is the final test Peter B. Parker gives Miles to prove he is ready to be Spider-Man?', '{"Save someone", "Defeat a villain", "Control his powers", "Create a web"}', 'Control his powers'),
(4, 'Which character does NOT know Miles'' secret identity by the end of "Into the Spider-Verse"?', '{"His father", "His mother", "Peter B. Parker", "Gwen Stacy"}', 'His mother'),
(4, 'What unique style does "Into the Spider-Verse" feature that other Spider-Man films do not?', '{"Anime", "Claymation", "Comic book style animation", "Stop-motion"}', 'Comic book style animation'),
(4, 'How does Miles initially react to his spider abilities?', '{"He is excited", "He ignores them", "He is scared", "He uses them immediately"}', 'He is scared'),
(4, 'What ability does Miles struggle to control at first?', '{"Web-slinging", "Super strength", "Invisibility", "Electrostatic discharge"}', 'Invisibility'),
(4, 'What does Kingpin hope to achieve with the Collider?', '{"Create a new world", "Bring his family back", "Gain superpowers", "Destroy New York"}', 'Bring his family back'),
(4, 'What theme is central to Miles Morales'' journey in "Into the Spider-Verse"?', '{"Revenge", "Acceptance", "Identity", "Love"}', 'Identity'),
(4, 'What personal loss does Peter B. Parker share with Miles?', '{"Loss of a career", "Divorce", "Loss of a loved one", "Loss of his powers"}', 'Divorce'),
(4, 'In "Into the Spider-Verse", what helps Miles unleash his full potential?', '{"A new gadget", "A motivational speech", "A leap of faith", "A fight"}', 'A leap of faith'),
(4, 'Who does Miles save from Kingpin during the final battle?', '{"His mother", "His father", "Peter B. Parker", "The whole city"}', 'The whole city'),
(4, 'Which Spider-Person tells Miles that they too lost someone important?', '{"Spider-Man Noir", "Spider-Ham", "Peni Parker", "All of them"}', 'All of them'),
(4, 'What personal project does Jefferson Davis dislike but Miles loves?', '{"Graffiti", "Robotics", "Basketball", "Music"}', 'Graffiti'),
(4, 'Which character in "Into the Spider-Verse" relates to Miles'' struggle with expectations?', '{"Spider-Woman", "Spider-Man Noir", "Peter B. Parker", "Gwen Stacy"}', 'Peter B. Parker'),
(4, 'What does Miles do that finally convinces Peter B. Parker he is ready to be Spider-Man?', '{"He defeats a villain alone", "He saves someone", "He masters his powers", "He makes his own suit"}', 'He masters his powers');
