-- Seed questions for "Classic Spiderman" (Subject ID: 1)
INSERT INTO questions (subject_id, question, options, answer) VALUES
(1, 'What is the real name of Classic Spider-Man?', '{"Peter Parker", "Miles Morales", "Ben Parker", "Harry Osborn"}', 'Peter Parker'),
(1, 'Who is the main antagonist in "Spider-Man" (2002)?', '{"Green Goblin", "Doctor Octopus", "Sandman", "Venom"}', 'Green Goblin'),
(1, 'What motivates Peter Parker to become Spider-Man?', '{"Revenge", "Adventure", "A school project", "Responsibility"}', 'Responsibility'),
(1, 'What is Peter Parker''s profession?', '{"Photographer", "Teacher", "Journalist", "Scientist"}', 'Photographer'),
(1, 'How does Spider-Man acquire his powers?', '{"Genetic mutation", "Born with them", "Laboratory accident", "Military experiment"}', 'Genetic mutation'),
(1, 'Who did Peter Parker fight in his first wrestling match as Spider-Man?', '{"Bonesaw McGraw", "The Undertaker", "Hulk Hogan", "Macho Man"}', 'Bonesaw McGraw'),
(1, 'What is the name of Peter Parker''s first love interest?', '{"Mary Jane Watson", "Gwen Stacy", "Felicia Hardy", "Liz Allan"}', 'Mary Jane Watson'),
(1, 'Which newspaper does Peter Parker work for?', '{"Daily Planet", "Daily Bugle", "New York Times", "Gotham Gazette"}', 'Daily Bugle'),
(1, 'Who discovers Peter Parker''s secret identity in the first film?', '{"Harry Osborn", "Mary Jane Watson", "Norman Osborn", "Aunt May"}', 'Mary Jane Watson'),
(1, 'What tragedy pushes Peter to become Spider-Man?', '{"The death of Uncle Ben", "The death of his parents", "A terrorist attack", "Being bullied"}', 'The death of Uncle Ben'),
(1, 'What high school does Peter Parker attend in the movie?', '{"Midtown High School", "Queensborough High", "New York High", "Brooklyn Academy"}', 'Midtown High School'),
(1, 'What event does Peter Parker take pictures at, which leads to the first battle with Green Goblin?', '{"A festival", "A graduation", "A wedding", "A parade"}', 'A festival'),
(1, 'Which character becomes the New Goblin in the Spider-Man films?', '{"Harry Osborn", "Norman Osborn", "Eddie Brock", "Flash Thompson"}', 'Harry Osborn'),
(1, 'Who is responsible for creating the serum that turns Norman Osborn into the Green Goblin?', '{"Dr. Otto Octavius", "Dr. Curt Connors", "Dr. Mendel Stromm", "Dr. Richard Parker"}', 'Dr. Mendel Stromm'),
(1, 'In "Spider-Man 2", what does Peter Parker deliver as a part-time job?', '{"Newspapers", "Pizzas", "Mail", "Groceries"}', 'Pizzas'),
(1, 'What is the name of Mary Jane''s fiancé in "Spider-Man 2"?', '{"John Jameson", "Harry Osborn", "Mark Allan", "Tony Stark"}', 'John Jameson'),
(1, 'Which character tells Peter Parker, "With great power, comes great responsibility"?', '{"Uncle Ben", "Aunt May", "Mary Jane Watson", "Norman Osborn"}', 'Uncle Ben'),
(1, 'What does Peter Parker study in college?', '{"Physics", "Chemistry", "Biology", "Engineering"}', 'Physics'),
(1, 'Who is the villain in "Spider-Man 3" that is a result of an alien symbiote?', '{"Green Goblin", "Doctor Octopus", "Venom", "Sandman"}', 'Venom'),
(1, 'How does Peter Parker initially try to manage his dual life as a student and a superhero in "Spider-Man 2"?', '{"He quits school", "He gives up being Spider-Man", "He tells Mary Jane his secret", "He uses time management software"}', 'He gives up being Spider-Man'),
(1, 'What is the name of the actor who plays the original J. Jonah Jameson?', '{"J.K. Simmons", "Willem Dafoe", "James Franco", "Tobey Maguire"}', 'J.K. Simmons'),
(1, 'What color is the suit worn by Classic Spider-Man?', '{"Red and Blue", "Black and Silver", "Green and Yellow", "Red and Gold"}', 'Red and Blue'),
(1, 'In "Spider-Man" (2002), who is Peter Parker''s competitor for Mary Jane''s affection?', '{"Harry Osborn", "Flash Thompson", "Eddie Brock", "John Jameson"}', 'Flash Thompson'),
(1, 'What is the main profession of Peter Parker''s Aunt May?', '{"Teacher", "Nurse", "Retired", "Librarian"}', 'Retired'),
(1, 'Which villain kidnaps Mary Jane in the first Spider-Man movie?', '{"Green Goblin", "Doctor Octopus", "Venom", "Sandman"}', 'Green Goblin'),
(1, 'In "Spider-Man 2", what major event does Peter Parker miss due to his responsibilities as Spider-Man?', '{"His graduation", "His birthday", "Mary Jane''s play", "Aunt May''s surgery"}', 'Mary Jane''s play'),
(1, 'What substance is Sandman made of in "Spider-Man 3"?', '{"Sand", "Water", "Fire", "Metal"}', 'Sand'),
(1, 'Which character becomes Venom in "Spider-Man 3"?', '{"Eddie Brock", "Harry Osborn", "Dr. Curt Connors", "Norman Osborn"}', 'Eddie Brock'),
(1, 'What is the source of Spider-Man''s powers in the Raimi trilogy?', '{"A radioactive spider bite", "A science experiment", "Alien technology", "Genetic modification"}', 'A radioactive spider bite'),
(1, 'What does Peter Parker sell to buy Mary Jane a gift in "Spider-Man 2"?', '{"His bike", "His camera", "His textbooks", "Spider-Man photos"}', 'Spider-Man photos'),
(1, 'In the first Spider-Man film, who is Peter Parker''s field trip buddy?', '{"Harry Osborn", "Mary Jane Watson", "Gwen Stacy", "Liz Allan"}', 'Harry Osborn'),
(1, 'What triggers Peter Parker''s transformation into Spider-Man?', '{"A car accident", "A gunshot", "A spider bite", "A chemical spill"}', 'A spider bite'),
(1, 'What is Mary Jane Watson''s dream job?', '{"Actress", "Model", "Singer", "Dancer"}', 'Actress'),
(1, 'What theme park ride does Mary Jane compare swinging with Spider-Man to?', '{"Rollercoaster", "Ferris wheel", "Bumper cars", "Log flume"}', 'Rollercoaster'),
(1, 'Which villain did Spider-Man fight at a bank?', '{"Doctor Octopus", "Green Goblin", "Venom", "Sandman"}', 'Doctor Octopus'),
(1, 'In "Spider-Man 3", who is the new love interest that creates a love triangle?', '{"Gwen Stacy", "Felicia Hardy", "Betty Brant", "Liz Allan"}', 'Gwen Stacy'),
(1, 'What building does the final battle in "Spider-Man" (2002) take place on?', '{"A bridge", "A tower", "A library", "A skyscraper"}', 'A skyscraper'),
(1, 'What device does Green Goblin offer to make Spider-Man evil?', '{"A ring", "A mask", "A serum", "A necklace"}', 'A serum'),
(1, 'What is the name of the newspaper editor who frequently criticizes Spider-Man?', '{"J. Jonah Jameson", "Ben Urich", "Eddie Brock", "George Stacy"}', 'J. Jonah Jameson'),
(1, 'How does Harry Osborn find out Peter is Spider-Man?', '{"He sees him changing", "He finds his suit", "Peter tells him", "Through a mutual friend"}', 'He finds his suit');