-- Seed questions for "The Amazing Spider-Man" (Subject ID: 2)
INSERT INTO questions (subject_id, question, options, answer) VALUES
(2, 'What is Peter Parker''s father''s name in "The Amazing Spider-Man"?', '{"Richard Parker", "Ben Parker", "Harry Osborn", "Norman Osborn"}', 'Richard Parker'),
(2, 'Who is the main villain in "The Amazing Spider-Man"?', '{"Lizard", "Electro", "Green Goblin", "Rhino"}', 'Lizard'),
(2, 'What does Peter Parker discover in his father''s briefcase?', '{"Glasses", "Formula", "Photos", "Passport"}', 'Formula'),
(2, 'Who is Peter''s love interest in "The Amazing Spider-Man"?', '{"Gwen Stacy", "Mary Jane Watson", "Felicia Hardy", "Liz Allan"}', 'Gwen Stacy'),
(2, 'What is the name of the Oscorp employee who becomes the Lizard?', '{"Curt Connors", "Max Dillon", "Harry Osborn", "Norman Osborn"}', 'Curt Connors'),
(2, 'How does Peter Parker get bitten by the spider in "The Amazing Spider-Man"?', '{"In a lab at school", "In a subway", "At Oscorp", "In his backyard"}', 'At Oscorp'),
(2, 'What device does Peter create to help him swing from buildings?', '{"Web-shooters", "Jet pack", "Grappling hook", "Magic rope"}', 'Web-shooters'),
(2, 'What happens to Gwen''s father at the end of "The Amazing Spider-Man"?', '{"He retires", "He moves away", "He dies", "He becomes a villain"}', 'He dies'),
(2, 'In "The Amazing Spider-Man 2", who is the main antagonist?', '{"Green Goblin", "Lizard", "Electro", "Vulture"}', 'Electro'),
(2, 'What tragedy strikes Gwen Stacy in "The Amazing Spider-Man 2"?', '{"She moves to England", "She breaks up with Peter", "She dies", "She loses her job"}', 'She dies'),
(2, 'What is the first thing Peter does with his powers in "The Amazing Spider-Man"?', '{"Saves a child", "Fights crime", "Gets revenge", "Plays basketball"}', 'Plays basketball'),
(2, 'Who tells Peter Parker, "With great power comes great responsibility" in "The Amazing Spider-Man"?', '{"Uncle Ben", "Aunt May", "Captain Stacy", "Gwen Stacy"}', 'Uncle Ben'),
(2, 'What high school do Peter Parker and Gwen Stacy attend?', '{"Midtown High School", "Oscorp Academy", "Science High", "Brooklyn Visions Academy"}', 'Midtown High School'),
(2, 'What part of New York does Peter Parker live in in "The Amazing Spider-Man"?', '{"Queens", "Brooklyn", "Manhattan", "Bronx"}', 'Queens'),
(2, 'How does Electro get his powers in "The Amazing Spider-Man 2"?', '{"Nuclear accident", "Genetic mutation", "Electrical accident", "Spider bite"}', 'Electrical accident'),
(2, 'Which character turns into the Green Goblin in "The Amazing Spider-Man 2"?', '{"Harry Osborn", "Norman Osborn", "Curt Connors", "Max Dillon"}', 'Harry Osborn'),
(2, 'What is Gwen Stacy''s job/internship in "The Amazing Spider-Man 2"?', '{"Reporter", "Research assistant", "Science intern at Oscorp", "Photographer"}', 'Science intern at Oscorp'),
(2, 'Where does the major showdown with Lizard take place in "The Amazing Spider-Man"?', '{"Times Square", "Statue of Liberty", "Oscorp Tower", "Sewers"}', 'Oscorp Tower'),
(2, 'What motivates Curt Connors to turn into the Lizard?', '{"To regenerate his arm", "Revenge", "To take over the city", "Money"}', 'To regenerate his arm'),
(2, 'Where does Peter first use his powers in a public setting in "The Amazing Spider-Man"?', '{"At a party", "In a subway", "At school", "On a bridge"}', 'In a subway'),
(2, 'What does Peter use to find the Lizard''s lair in "The Amazing Spider-Man"?', '{"A map", "GPS", "A tracker", "His camera"}', 'A tracker'),
(2, 'What happens to Dr. Connors at the end of "The Amazing Spider-Man"?', '{"He escapes", "He dies", "He''s arrested", "He turns back into a lizard"}', 'He''s arrested'),
(2, 'What theme is heavily explored in "The Amazing Spider-Man 2"?', '{"Revenge", "Identity", "Power", "Love"}', 'Identity'),
(2, 'How does Peter Parker meet Gwen Stacy in "The Amazing Spider-Man"?', '{"At Oscorp", "At school", "Through Aunt May", "At a party"}', 'At school'),
(2, 'Who helps Electro enhance his powers in "The Amazing Spider-Man 2"?', '{"Harry Osborn", "Curt Connors", "Norman Osborn", "Rhino"}', 'Harry Osborn'),
(2, 'What iconic structure does Spider-Man battle Electro on in "The Amazing Spider-Man 2"?', '{"Brooklyn Bridge", "Empire State Building", "Times Square", "Central Park"}', 'Times Square'),
(2, 'In "The Amazing Spider-Man 2", what significant event does Peter Parker miss due to being Spider-Man?', '{"Gwen''s graduation", "His own birthday", "Aunt May''s surgery", "His mother''s memorial"}', 'Gwen''s graduation'),
(2, 'What clue leads Peter to discover more about his father''s work in "The Amazing Spider-Man"?', '{"An old photograph", "A hidden letter", "A briefcase", "A secret lab"}', 'A briefcase'),
(2, 'What is the name of the project that created the spiders?', '{"Project Spider", "Project Web", "Project Arachnid", "Project Venom"}', 'Project Arachnid'),
(2, 'What role does Felicia play in "The Amazing Spider-Man 2"?', '{"Harry''s assistant", "Norman''s caretaker", "A scientist at Oscorp", "A journalist"}', 'Harry''s assistant'),
(2, 'What is Peter Parker accused of at school?', '{"Cheating", "Stealing", "Bullying", "Skipping class"}', 'Cheating'),
(2, 'What does Peter promise Gwen''s father?', '{"He will leave New York", "He will stop being Spider-Man", "He will take care of Gwen", "He will give up his powers"}', 'He will take care of Gwen'),
(2, 'Which character discovers Spider-Man''s true identity in "The Amazing Spider-Man"?', '{"Gwen Stacy", "Captain Stacy", "Harry Osborn", "Electro"}', 'Captain Stacy'),
(2, 'What is the final battle location in "The Amazing Spider-Man 2"?', '{"An Oscorp laboratory", "A power grid station", "A bridge", "A school"}', 'A power grid station'),
(2, 'Who is the founder of Oscorp in the Amazing Spider-Man series?', '{"Norman Osborn", "Otto Octavius", "Peter''s father", "Harry Osborn"}', 'Norman Osborn'),
(2, 'What does Spider-Man use to defeat Electro?', '{"Water", "A car", "Magnetism", "Fire"}', 'Magnetism'),
(2, 'Who narrates the opening of "The Amazing Spider-Man"?', '{"Peter Parker", "Gwen Stacy", "Richard Parker", "Mary Parker"}', 'Richard Parker'),
(2, 'In "The Amazing Spider-Man", what does Peter buy at the convenience store?', '{"Chocolate milk", "A sandwich", "A lottery ticket", "Soda"}', 'Chocolate milk'),
(2, 'What object does Peter use to signal Gwen he is outside her window?', '{"A flashlight", "A laser pointer", "His phone", "Fireworks"}', 'A flashlight'),
(2, 'What high-stakes situation does Spider-Man diffuse at the end of "The Amazing Spider-Man"?', '{"A bomb threat", "A hostage situation", "A reactor meltdown", "A biological attack"}', 'A biological attack');
